name: Enviar alertas para Discord

on:
  push:
    branches:
      - main
      - desenvolvimento

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar alerta para Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "📢 Novo commit no repositório **${{ github.repository }}** no branch **${{ github.ref_name }}**. Autor: **${{ github.actor }}**. Mensagem: ${{ github.event.head_commit.message }}"
