name: Enviar alertas para Discord

on:
  push:
    branches:
      - main
      - desenvolvimento
  workflow_dispatch: # permite rodar manualmente pelo GitHub Actions

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar alerta para Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            📢 **Novo commit**
            Repositório: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Autor: ${{ github.actor }}
            Mensagem: ${{ github.event.head_commit.message }}
            Commit: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
