name: Enviar alertas para Discord

on:
  push:
    branches:
      - main
      - desenvolvimento

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar alerta para Discord
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          args: "Novo commit no repositório **${{ github.repository }}** no branch **${{ github.ref_name }}** pelo autor **${{ github.actor }}**. Mensagem: ${{ github.event.head_commit.message }}"
