- name: Compile Java files
  run: |
    mkdir -p out
    javac -cp junit-platform-console-standalone-1.10.0.jar -d out \
      App.java \
      src/AppTest.java \
      src/main/java/com/gimenes/Example.java \
      src/test/java/com/gimenes/ExampleTest.java
